ALTER SESSION SET CONTAINER = FREEPDB1;

-- Bronze schema
CREATE USER claims_bronze IDENTIFIED BY claims_bronze
DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE TO claims_bronze;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO claims_bronze;

-- Silver schema
CREATE USER claims_silver IDENTIFIED BY claims_silver
DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE TO claims_silver;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO claims_silver;

-- Gold schema
CREATE USER claims_gold IDENTIFIED BY claims_gold
DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE TO claims_gold;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO claims_gold;
